version: 0.2

env:
  variables:
    TF_ACTION: "apply"   # Puede ser "apply" o "destroy"

phases:
  install:
    commands:
      - echo "Instalando Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
      - unzip terraform_1.13.1_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Entrando en pre_build..."
      - cd environments/test
      - terraform init -input=false
  build:
    commands:
      - echo "Entrando en build phase con acción: $TF_ACTION"
        build:
    commands:
      - echo "Entrando en build phase con acción: $TF_ACTION"
      - bash -c 'if [ "$TF_ACTION" = "apply" ]; then
          terraform plan -input=false &&
          terraform apply -auto-approve -input=false;
        elif [ "$TF_ACTION" = "destroy" ]; then
          terraform plan -destroy -input=false &&
          terraform destroy -auto-approve -input=false;
        else
          echo "Acción no válida: $TF_ACTION" && exit 1;
        fi'

  post_build:
    commands:
      - echo "Entrando en post_build..."
      - echo "Acción $TF_ACTION completada correctamente."
