version: 0.2

env:
  variables:
    TF_ACTION: "destroy"   # Puede ser "apply" o "destroy"

phases:
  install:
    commands:
      - echo "Instalando Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
      - unzip terraform_1.13.1_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Entrando en pre_build..."
      - cd environments/test
      - terraform init -input=false
  build:
    commands:
      - echo 'Entrando en build phase con acci칩n:' $TF_ACTION
      - if [ "$TF_ACTION" = "apply" ]; then terraform plan -input=false; fi
      - if [ "$TF_ACTION" = "apply" ]; then terraform apply -auto-approve -input=false; fi
      - if [ "$TF_ACTION" = "destroy" ]; then terraform plan -destroy -input=false; fi
      - if [ "$TF_ACTION" = "destroy" ]; then terraform destroy -auto-approve -input=false; fi
      - if [ "$TF_ACTION" != "apply" ] && [ "$TF_ACTION" != "destroy" ]; then echo "Acci칩n no v치lida:" $TF_ACTION; exit 1; fi
  post_build:
    commands:
      - echo "Entrando en post_build..."
      - echo "Acci칩n $TF_ACTION completada correctamente."
