version: 0.2

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
      - unzip terraform_1.13.1_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      # Navega al directorio del entorno de pruebas.
      - cd environments/test
      # Inicializa Terraform, descargando módulos y el backend.
      - terraform init
  build:
    commands:
      - echo Entered the build phase...
      # Aplica los cambios de Terraform automáticamente sin solicitar confirmación.
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Entered the post_build phase...
      # Navega al directorio del entorno
      - cd environments/test
      # Muestra la IP pública de la instancia de EC2
      - echo "Despliegue de Terraform completado."