version: 0.2

phases:
install:
commands:
# Instala Terraform. Se recomienda una versión específica para consistencia.
- wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
- unzip terraform_1.0.0_linux_amd64.zip
- mv terraform /usr/local/bin/
pre_build:
commands:
# Navega al directorio del entorno de pruebas.
- cd environments/test
# Inicializa Terraform, descargando módulos y el backend.
- terraform init
build:
commands:
# Navega al directorio del entorno
- cd environments/test
# Aplica los cambios de Terraform automáticamente sin solicitar confirmación.
- terraform apply -auto-approve
post_build:
commands:
# Navega al directorio del entorno
- cd environments/test
# Muestra la IP pública de la instancia de EC2
- echo "Despliegue de Terraform completado."
- echo "La IP de la instancia es:"
- terraform output public_ip